import {Product} from "./product.interface";

export const products: Product[] = [
  {name: 'product1', slug: 'product1', description: 'jfgfgjkfg', img: 'https://bumper-stickers.ru/57602-large_default/deyl-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product2', slug: 'product2', description: 'jfgfgjkfg', img: 'https://interior-stickers.ru/57601-thickbox_default/chip-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product3', slug: 'product3', description: 'jfgfgjkfg', img: 'https://bumper-stickers.ru/57602-large_default/deyl-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product4', slug: 'product4', description: 'jfgfgjkfg', img: 'https://interior-stickers.ru/57601-thickbox_default/chip-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product5', slug: 'product5', description: 'jfgfgjkfg', img: 'https://bumper-stickers.ru/57602-large_default/deyl-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product1', slug: 'product6', description: 'jfgfgjkfg', img: 'https://bumper-stickers.ru/57602-large_default/deyl-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product2', slug: 'product7', description: 'jfgfgjkfg', img: 'https://interior-stickers.ru/57601-thickbox_default/chip-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product3', slug: 'product8', description: 'jfgfgjkfg', img: 'https://bumper-stickers.ru/57602-large_default/deyl-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product4', slug: 'product9', description: 'jfgfgjkfg', img: 'https://interior-stickers.ru/57601-thickbox_default/chip-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product5', slug: 'product10', description: 'jfgfgjkfg', img: 'https://bumper-stickers.ru/57602-large_default/deyl-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product1', slug: 'product11', description: 'jfgfgjkfg', img: 'https://bumper-stickers.ru/57602-large_default/deyl-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product2', slug: 'product12', description: 'jfgfgjkfg', img: 'https://interior-stickers.ru/57601-thickbox_default/chip-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product3', slug: 'product13', description: 'jfgfgjkfg', img: 'https://bumper-stickers.ru/57602-large_default/deyl-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product4', slug: 'product14', description: 'jfgfgjkfg', img: 'https://interior-stickers.ru/57601-thickbox_default/chip-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product5', slug: 'product15', description: 'jfgfgjkfg', img: 'https://bumper-stickers.ru/57602-large_default/deyl-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product1', slug: 'product16', description: 'jfgfgjkfg', img: 'https://bumper-stickers.ru/57602-large_default/deyl-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product2', slug: 'product17', description: 'jfgfgjkfg', img: 'https://interior-stickers.ru/57601-thickbox_default/chip-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product3', slug: 'product18', description: 'jfgfgjkfg', img: 'https://bumper-stickers.ru/57602-large_default/deyl-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product4', slug: 'product19', description: 'jfgfgjkfg', img: 'https://interior-stickers.ru/57601-thickbox_default/chip-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product5', slug: 'product20', description: 'jfgfgjkfg', img: 'https://bumper-stickers.ru/57602-large_default/deyl-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product1', slug: 'product21', description: 'jfgfgjkfg', img: 'https://bumper-stickers.ru/57602-large_default/deyl-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product2', slug: 'product22', description: 'jfgfgjkfg', img: 'https://interior-stickers.ru/57601-thickbox_default/chip-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product3', slug: 'product23', description: 'jfgfgjkfg', img: 'https://bumper-stickers.ru/57602-large_default/deyl-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product4', slug: 'product24', description: 'jfgfgjkfg', img: 'https://interior-stickers.ru/57601-thickbox_default/chip-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product5', slug: 'product25', description: 'jfgfgjkfg', img: 'https://bumper-stickers.ru/57602-large_default/deyl-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900},
  {name: 'product1', slug: 'product26', description: 'jfgfgjkfg', img: 'https://bumper-stickers.ru/57602-large_default/deyl-iz-multfilma-chip-i-deyl-speshat-na-pomoshh.jpg', category: 'category 2', price: 900}
];
